name: Deploy website after code push
on:
  push:
    branches:  
      - main
jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: thiesketelsen.de
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd /home/docker/letsencrypt/www
          ${{ secrets.SCRIPT}}
