name: Deploy website after code push
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: thiesketelsen.de
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd /home/docker/letsencrypt/www
          ${{ secrets.SCRIPT}}
